-- Enforcee — outreach seed.
-- Generated from an 11-agent recon of Reddit, HN, the Cursor and OpenAI forums,
-- GitHub issues and the newsletters. Run AFTER 0003_marketing.sql.
--
-- Standing rules and kill gates are seeded as their own cards so they sit on the board
-- rather than in a document nobody reopens.

insert into public.campaign_items (surface, kind, title, body, status, scheduled_for, constraints, notes, effort_hours, author) values
('Reddit — r/ClaudeAI, flair "Claude Code Workflow" (fallback: r/ClaudeCode, flair "Tips & Workflows")','post','I checked which of my CLAUDE.md rules actually left a trace. About a third of them leave none, and those are the ones I trusted most.','I have been trying to answer a boring question about my own CLAUDE.md: for any given session, which of these rules actually did anything?

Not "was the file loaded". Not "did the model say it read it". Did the rule leave something behind that I can point at.

So I took a real ruleset, split it into individual rules, and tried to decide each one against an actual session, using plain code first and only falling back to a model when code could not decide. Three things came out that I did not expect.

1. Most of a real ruleset does not need a model to check it. On the rulesets I have run, roughly 80% of rules are decided by code with zero model calls. "Use pnpm, never npm" is a question about the command log. "Do not touch package-lock.json" is a question about the diff. "Every new component gets a test file" is a question about the file tree. Nothing about that needs an LLM, and running an LLM over it just gives you a second thing that can be wrong.

2. The rules that made me feel safest are the ones that leave nothing behind. "Write clean code." "State your assumptions." "Ask before doing anything big." In a session where the model behaved and a session where it did not, those rules look identical from the outside. I stopped scoring them as followed and started marking them "no signal", and my honest number dropped hard. Ned Cole found the same thing by hand on the Cursor side: "vague rules like ''write clean code'' get ignored. specific rules like ''all type aliases must use the Branded prefix'' get followed." (https://forum.cursor.com/t/how-to-figure-out-why-your-cursor-rules-arent-working/152439)

3. On compaction, the folklore is off. Project-root CLAUDE.md is not the thing that dies. Anthropic documents that it gets re-read from disk and re-injected after /compact. What is documented as lost is narrower: rules with paths: frontmatter, until a matching file is read again; nested CLAUDE.md in subdirectories, until a file in that subdirectory is read again; and invoked skill bodies, which come back capped at 5,000 tokens per skill and 25,000 total, oldest dropped first, with truncation keeping the start of the file. (https://code.claude.com/docs/en/context-window) That last row is not "survives", it is a silent haircut, and I think it explains a lot of the reports that get written up as "my rules vanished".

One implementation note, because it is the part I got wrong first. If you use a model to judge whether a rule was followed, make it return the exact quote from the output that proves the verdict, then check that the quote literally exists in the output at the offset it claims. If it does not, throw the verdict away rather than showing it. Before I added that check, my judge occasionally produced a confident violation with a quote that was not in the transcript. After it, that failure mode is gone by construction.

Numbers, because claims without them are worthless here. A full audit of a real ruleset costs me $0.0057 and takes about 7 seconds. Judge accuracy against my hand-labelled gold set is 94% on Haiku 4.5. Across 48 verdicts on three models I got zero fabricated evidence spans and zero false accusations. That is 48 verdicts, not 4,800, so weigh it accordingly.

Disclosure, per rule 6: I built the thing I used to do this. It is called Enforcee (https://enforcee.vercel.app, source at https://github.com/7patriksz-art/Enforcee). You paste a ruleset and an output and get a per-rule verdict with the evidence quote. It is mine, I benefit if you use it, and I would rather say that at the top than have someone find it in my history. Nothing in this post requires it. The deterministic-first split and the literal-quote check are both things you can build yourself in an afternoon, and I would honestly like to see someone else''s numbers on the 80/20 split, because mine come from my own rulesets and that is a biased sample.

The question I actually want answered: if you have a rule you are sure is working, how do you know?

---
WHY THIS LANDS
It copies the shape that is currently working in the sub (SlashRevet''s "my ai writes 100% of the code, this is the thing i had to add to stop the project drifting", flair Claude Code Workflow): a first-person workflow finding, not a launch. It opens on a measurement, it corrects a piece of popular folklore with a doc citation rather than a vibe, and it ends with a question, which satisfies Rule 3 ("is your post likely to add positively to the knowledge of other readers"). It also answers the exact thing uncivilized_engineer and ximon16182 are asking in neighbouring subs: which rule phrasings actually hold.

RISK
Two real ones. First, r/ClaudeAI''s rules came from an archive (arctic-shift.photon-reddit.com), not a live sidebar, and no karma or account-age gate could be verified. Read the sidebar in a browser before posting and confirm Rule 6 still reads that way. Second, the 80% figure is from my own rulesets and someone will say so. That is why the post says it. If the sub reacts badly to any self-promotion at all, the fallback is to cut the disclosure paragraph and the links entirely and post it as a pure finding, then answer with the link only if someone asks what I used.','drafting',null,'r/ClaudeAI Rule 6 (promotion allowed if you fully disclose what the user gets, who it helps, and your association) is satisfied explicitly in the second-to-last paragraph. Rule 5 (flair mandatory) is handled by using an observed live flair. Rule 3 (be helpful) and Rule 7 (stay grounded, no anthropomorphising) are respected: no claim about what the model "wanted" or "decided". The compaction hard rule is respected, the post explicitly says project-root CLAUDE.md is re-injected and names only the three genuinely-lost categories. Both zero-claims are bound to their sample size in the same sentence, per the clarkesdirective warning. No "compliance", "governance", "platform" or "layer" anywhere.','Raw material from research. Rewrite every sentence in your own words before posting — several of these surfaces ban generated text outright.',1.5,'claude'),
('GitHub comment — openai/codex issue #25884 (https://github.com/openai/codex/issues/25884, open, labels CLI/bug/context/m','comment','Comment on "AGENTS.md behaves more like a soft hint than a durable operating constraint"','The phrase "soft hint rather than a durable operating constraint" matches what I see, and I want to try to split it into two failure modes, because they are indistinguishable from the chair and have different fixes.

(a) The rule never reached the model.
(b) The rule reached the model and was not applied.

For (a) there is already a confirmed mechanical cause on this tracker: #13386, AGENTS.md silently truncated at 32 KB with no warning. Any rule past that boundary is not a model-behaviour question at all, and if some of your file is past it, every conclusion you draw about "Codex ignores my rules" is contaminated.

Here is a repro that separates them. It is deliberately dumb so that the result is not arguable.

1. Build an AGENTS.md where every rule has a mechanically observable signature, so "followed" is decidable from artifacts rather than from reading vibes. For example: "Every file you create must begin with the line // rule-07". "Never run npm; use pnpm." "Do not modify any file under vendor/."

2. Duplicate the same rule set twice in the file, with different signatures, so that set A sits well under 32 KB and set B sits well past it. Pad between them with inert prose. Now the only difference between A and B is byte offset.

3. Run one task that should trigger every rule in both sets. Record, per rule: did the signature appear, was the forbidden command in the shell log, was the forbidden path in the diff.

4. Then run a second, long session that stays entirely under the cap, and record the same per-rule result turn by turn, so you get a decay curve rather than a single yes/no.

If set B fails while set A passes, that is #13386 and it is a byte problem. If both sets pass early and set A degrades over turns, that is the thing this issue is about, and the degradation is now a number rather than an impression.

What I get when I run this: [FOUNDER, PASTE YOUR ACTUAL NUMBERS HERE. Codex version, model, number of rules in each set, how many produced their signature in each set, and at which turn index the first under-cap rule stopped producing its signature. Do not post this comment without having run it.]

Two things I could not verify and am not going to assert: I have not confirmed the 32 KB figure independently against a current build, I am taking it from #13386. And a rule that produces no signature is not automatically a violated rule. Plenty of rules cannot produce evidence either way, which is its own problem and probably the more interesting one.

For transparency: I wrote a tool that does the per-rule classification and the diff/log checking for me, and it is mine, so discount accordingly (https://github.com/7patriksz-art/Enforcee). The repro above does not need it. The part worth stealing regardless of tooling is the paired under-cap/over-cap rule sets, because that is what turns "it ignores my instructions" into something a maintainer can act on.

---
WHY THIS LANDS
It follows the only pattern that works in maintainer threads: reproduction first, tool second, one comment, no link drop. It gives cellis-saasoptics something he can run today and gives the maintainers something triageable. It also connects two open issues (#25884 and #13386) in a way nobody in either thread has, which is a genuine contribution rather than a pitch.

RISK
The comment is worthless and actively damaging if posted with the placeholder unfilled or with numbers that were not actually produced. This audience will run it. Also: if the 32 KB cap has been fixed since #13386 was filed on 2026-03-03, step 2 produces a null result and the comment looks uninformed. Check the current behaviour before posting, and if it is fixed, say so in the comment, that is itself a useful contribution to the thread. Finally, do not repeat this same comment on other issues; identical text across threads is what gets an account flagged as spam.','drafting',null,'No repo-specific self-promotion rule exists here, so the governing constraint is GitHub''s acceptable use plus maintainer patience: one comment, on an open issue, with a reproduction, tool mentioned once at the end with an explicit conflict-of-interest note. It does not touch Anthropic''s compaction behaviour at all, so the CLAUDE.md hard rule is not in play. It states plainly which numbers are second-hand (the 32 KB figure) and refuses to equate "no signal" with "violated".','Raw material from research. Rewrite every sentence in your own words before posting — several of these surfaces ban generated text outright.',1.5,'claude'),
('Hacker News — Show HN','post','Show HN: Enforcee – per-rule verdicts on whether an AI coding agent followed your rules','TEXT FIELD / FIRST COMMENT:

You paste a ruleset (CLAUDE.md, AGENTS.md, .cursorrules, or a raw system prompt) and an AI output. You get one row per rule: followed, violated, not applicable, or unverifiable, each with the exact quote from the output that decided it and the character offset where that quote lives. No signup, no email, nothing to install to try it: https://enforcee.vercel.app . Source: https://github.com/7patriksz-art/Enforcee .

The mechanism, which is the only part I think is interesting:

About 80% of a realistic ruleset is decided by ordinary code with zero model calls. "Use pnpm" is a question about the command log. "Do not edit generated files" is a question about the diff. Running a model over those gives you a second thing that can be wrong for no benefit. Only the residue goes to a model judge.

The judge has to return the substring of the output that justifies its verdict. That substring is then checked against the output. If it is not literally there, the verdict is discarded and the rule is recorded as unverifiable rather than as a violation. Failing closed like this is why the accuracy numbers below are about false accusations rather than about overall agreement.

Measurements, all mine, all reproducible from the repo: $0.0057 and about 7 seconds for a full audit. 94% agreement with my hand-labelled gold set using Haiku 4.5 as the judge. Zero false accusations and zero fabricated evidence spans across 48 verdicts on three models. Forty-eight is a small n and I would rather say that here than have it extracted from me in the thread.

The headline number in the product is coverage, meaning the share of applicable rules that left any observable trace. It is usually worse than people expect, and it is not a score of your assistant, it is a property of your ruleset. "Write clean code" cannot leave a trace. That is the finding that made me build this: the rules I trusted most were the ones I had no way to check.

Three things I want to pre-empt, because they are fair.

Compaction. I am not claiming your project-root CLAUDE.md is dropped at compaction. Anthropic documents that it is re-read from disk and re-injected. What is documented as lost is narrower: paths:-scoped rules, nested CLAUDE.md in subdirectories, and invoked skill bodies which return capped at 5,000 tokens per skill and 25,000 total, oldest dropped first (https://code.claude.com/docs/en/context-window). The PostCompact hook I generate re-injects the ruleset, which is useful for that narrow set and unnecessary for project-root CLAUDE.md.

PreToolUse denials. My guard is 10/10 on my enforcement cases, but PreToolUse deny is contested on Anthropic''s own tracker: https://github.com/anthropics/claude-code/issues/37210 reports a well-formed deny with exit code 2 being ignored for the Edit tool, and #4669 and #4362 report similar for MCP tools. My 10/10 was measured on [FOUNDER: EXACT CLAUDE CODE VERSION] against [FOUNDER: EXACT TOOL NAMES]. I have not tested every tool type and I would not claim the guard is unconditional.

What it is not. It does not tell you your code is correct, and a rule that leaves no trace stays unverifiable no matter how much you want an answer. If your complaint is that the interesting rules are exactly the uncheckable ones, I agree, and the honest use of this is to find out which of your rules you are taking on faith.

What I would most like from this thread: try to make it accuse you of something you did not do. If you can produce a false accusation or an evidence quote that is not in the output, I want the input.

---
WHY THIS LANDS
It breaks every element of the pattern that is currently getting Show HNs flagged: no signup wall, source available, mechanism before product, measured numbers in the first third, and an explicit invitation to falsify. It answers the question that killed the closest precedent in this exact niche (Tanishq0333''s Show HN, where the first substantive comment was "any benchmarks?") before it is asked. Pre-empting the PreToolUse bug report is worth more than the objection never being raised: if someone posts issue #37210 under an unprepared launch, the thread is over.

RISK
Highest-risk item on the list and it should go last, not first. There is an active flagging wave on Show HN (https://news.ycombinator.com/item?id=48460938, https://news.ycombinator.com/item?id=48384741) and a green username under two weeks old plus a product plus a paid service is the exact pattern being killed. Read dang''s explanation at https://news.ycombinator.com/item?id=48455315 first, which I could not load (it returned 429). Before launching: several weeks of real commenting from an aged account, know someone who can vouch, and fill in the two version placeholders. Also: Enforcee is a paid service, and "paid" plus "new account" is half the pattern being flagged, so the free no-signup audit needs to genuinely work for a stranger with no card.','drafting',null,'Show HN''s own rules: something people can play with, easy to try without signups or emails, not a blog post or a sign-up page. The title carries no gratuitous number, no uppercase, no exclamation, and none of compliance, governance, platform or layer. Every claim about compaction is doc-cited and narrow. The prose must be typed by hand: HN''s guidelines say verbatim "Don''t post generated text or AI-edited text", which is stricter than most, so treat this draft as notes to rewrite rather than text to paste.','Raw material from research. Rewrite every sentence in your own words before posting — several of these surfaces ban generated text outright.',1.5,'claude'),
('dev.to — opener for a long-form technical piece (cross-post canonical to Hashnode)','article','Hooks stopped my rules from being ignored. They still couldn''t tell me which rules were working.','OPENER (first ~600 words of the piece; the rest is the method and the numbers):

In April, Mike Dolan published a post here called "I Wrote 500 Lines of Rules for Claude Code. Here''s How I Made It Actually Follow Them" (https://dev.to/mikeadolan/i-wrote-500-lines-of-rules-for-claude-code-heres-how-i-made-it-actually-follow-them-3c8). Two lines from it have been sitting in my head since:

"Rules in a text file are suggestions."

"If a rule matters, it needs a hook."

I think both are right, and I went and did the same thing. I wrote the hooks. Violations of the rules I hooked went to roughly nothing, same as he reports. And then I hit the part he does not cover, which is the part I actually care about now.

A hook can only enforce a rule you can express as a predicate over a tool call. "Never run npm install in this repo" is a hook. "Never write to src/generated" is a hook. When I went through my own rules file and asked which of them I could turn into a hook, the answer was: fewer than half. Everything else was either about the content of the code the model wrote, or it was advice.

So the file splits into three groups, and I did not realise this until I tried to check the file rule by rule instead of reading it top to bottom.

Group one: rules a hook can block before they happen. These are solved. Write the hook, stop thinking about them.

Group two: rules a hook cannot block but code can check afterwards. "Every new component has a matching test file" is not a tool-call predicate you can evaluate at deny-time, but it is trivially checkable against the diff once the turn is done. This group is bigger than I expected. On the rulesets I have run, group one and group two together come to about 80% of the rules, and none of that 80% needs a model to adjudicate it. It needs grep, a diff, and the command log.

Group three: rules that cannot produce evidence at all. "Write clean code." "Prefer simple solutions." "State your assumptions explicitly." These are the rules I spent the most time wording and the ones I would have told you were most important. There is no artifact anywhere in the session that distinguishes a turn where the model honoured them from a turn where it did not. Not a hook problem. Not a model problem. They are unfalsifiable by construction, and until I started scoring them separately I was quietly counting them as working.

That third group is why "my rules are being followed" felt true to me for months while the diffs said otherwise. I was checking the rules that were easy to check and inferring the rest.

This piece is about what happened when I stopped inferring. I split a real ruleset into atomic rules, built a decision procedure for each one that runs against the actual session artifacts, sent only the leftovers to a model judge, and made the judge''s verdict invalid unless the quote it cited literally appears in the output. Then I ran it across three models and counted how often it lied.

Specifically I am going to show you:

- how to classify a rule by the evidence it can produce, which is a five-minute exercise you can do on your own file today without any tooling
- why the model judge needs a literal-substring gate, with the fabricated evidence span that convinced me
- what the numbers came out as: $0.0057 and about 7 seconds per full audit, 94% agreement with a hand-labelled gold set on Haiku 4.5, and zero fabricated spans across 48 verdicts on three models, which is a small sample and I will say so again later
- the one thing hooks genuinely do fix that nothing else does, and the narrower-than-you-think set of things that actually go missing at compaction

One correction before I start, because it is load-bearing and I see it repeated constantly. Project-root CLAUDE.md is not lost at compaction. Anthropic''s docs say it gets re-read from disk and re-injected. What is documented as lost is paths:-scoped rules until a matching file is read again, nested CLAUDE.md in subdirectories, and invoked skill bodies, which come back capped at 5,000 tokens per skill and 25,000 total with the oldest dropped first (https://code.claude.com/docs/en/context-window). If your mental model is "the file dies", you are debugging the wrong thing.

---
WHY THIS LANDS
It is a direct, credited continuation of the single highest-performing post on this exact topic on this exact platform, and it adds the thing that post lacks: measurement per rule rather than an aggregate impression across sessions. It uses the vocabulary people actually search (ignored, forgets, lost after compact) in the body while keeping the title concrete. The three-group classification is genuinely useful with no tooling at all, which is what keeps it from reading as an ad.

RISK
The piece only works if the numbers section is real and the fabricated-evidence-span example is an actual one from your logs, not a hypothetical. If you cannot produce that span, cut the bullet. Secondary risk: rulestack published "What survives compaction in Claude Code" on 21 Jul 2026 covering the same correction while selling a rules pack, so the compaction paragraph is not novel and should stay a correction in passing, not a section. Do not let the piece drift into being a compaction post.','drafting',null,'dev.to''s AI-assisted article guidelines (https://dev.to/guidelines-for-ai-assisted-articles-on-dev) say an AI-assisted post must not promote any business or program including your own, and the penalty is reduced visibility across all your posts, not just the offending one. So: either this is typed by hand and can mention Enforcee once at the very end, or it is drafted with assistance and mentions no product at all. As written the opener names no product, which is the safe default. It also respects the compaction hard rule with a doc citation, and it credits Mike Dolan by name and link rather than framing him as wrong.','Raw material from research. Rewrite every sentence in your own words before posting — several of these surfaces ban generated text outright.',1.5,'claude'),
('Short reply template — for comment threads where someone says their rules are being ignored (r/cursor, r/ClaudeCode, for','comment','Reply template: "my rules are being ignored"','Before assuming the model is ignoring you, it is worth separating three things, because they look identical and have different fixes.

Did the rule load? Frontmatter is the usual culprit on the Cursor side. Ned Cole catalogued seven silent ways a rule fails to load, including a missing closing --- in the frontmatter and the .mdc version silently winning over .cursorrules when you have both: https://forum.cursor.com/t/how-to-figure-out-why-your-cursor-rules-arent-working/152439 . On the Codex side there is a hard mechanical one, AGENTS.md is silently truncated at 32 KB with no warning: https://github.com/openai/codex/issues/13386 .

Did the rule load and then get contradicted? In that same Cursor thread, Diego resolved his case by finding two of his own rules that contradicted each other. Worth grepping your file for pairs before blaming the model.

Did the rule load, survive, and still leave no trace? This is the one people miss. If the rule is "write clean code" or "be careful with edge cases", there is no artifact in the session that could tell you whether it was followed. It is not being ignored, it is unfalsifiable. Rewrite it as something a diff or a command log can answer, or accept that you are taking it on faith.

The quick version: pick your three most important rules and ask, for each one, what would I grep for to prove it was followed. If you cannot answer that, the rule cannot be enforced by anything, including a hook.

---
WHY THIS LANDS
It is useful on its own, links nothing of mine, and cites two named sources plus a vendor tracker. In threads where a competitor drops a product link, this is the comment that gets upvoted. It also plants the coverage idea (a rule that cannot leave a trace) without naming it, which means when someone asks "is there a tool for this", the answer is invited rather than pushed.

RISK
Low, with one caveat: do not paste it verbatim more than a few times. Identical comment text across threads is the single easiest way to get read as a bot on Reddit and flagged as spam by GitHub. Rewrite the middle two paragraphs each time to fit the specific person''s setup, and only answer threads where the details actually match. Also verify the 32 KB truncation is still current before citing it; that issue was filed 2026-03-03.','drafting',null,'Works under every self-promo regime on the list because it contains no link to my own work: r/cursor (rules unverified, so assume the strictest), r/ChatGPTCoding Rules 1/4/6, forum.cursor.com''s 10% self-promotion cap and its accuracy rule about claims regarding Cursor and competitors, and GitHub''s spam norms. Makes no compaction claim at all. Under 250 words, which is what a comment should be.','Raw material from research. Rewrite every sentence in your own words before posting — several of these surfaces ban generated text outright.',1.5,'claude'),
('awesome-claude-code (hesreallyhim) — web issue form submission, https://github.com/hesreallyhim/awesome-claude-code/issu','submission','Submission fields + one-line description','Display Name: Enforcee
Category: Linting
Primary Link: https://github.com/7patriksz-art/Enforcee
Author: 7patriksz-art
License: [FOUNDER: must be a real LICENSE file in the repo root that GitHub''s license detection picks up. MIT unless you have a reason otherwise. The maintainer''s bot reads this.]

Description (one line, this is the submission line):
Audits an AI coding session against a CLAUDE.md, AGENTS.md, or .cursorrules ruleset and returns a per-rule verdict with an evidence quote verified to exist in the output, plus generated PreToolUse and PostCompact hooks and a local decision ledger.

Shorter variant if the form or a maintainer wants it tighter:
Returns a per-rule followed/violated/unverifiable verdict for a CLAUDE.md or AGENTS.md ruleset against an actual session output, with each verdict anchored to a quote checked to exist in that output.

Markdown-format line, for the PR-based lists instead (jqueryscript/awesome-claude-code, Tools & Utilities; webfuse-com/awesome-claude):
- [Enforcee](https://github.com/7patriksz-art/Enforcee) - Audits an AI coding session against a CLAUDE.md or AGENTS.md ruleset and returns a per-rule verdict with an evidence quote verified to exist in the output.

---
WHY THIS LANDS
The existing Linting entries (agnix, Ctxlint) validate rule files. This one says what it does differently in the first clause: it audits a session output, not the ruleset. That distinction has to be in the sentence or the maintainer reads it as another linter and closes it. The register matches the list''s mandated style: a description, not a pitch, one line, no reader-address, no emoji, no adjectives.

RISK
Hard automated gate: the repo must be at least 14 days old measured from the first commit on the default branch with visible ongoing commits after day one, or have 100+ stars, otherwise the bot closes the issue and the submission is burned. The Enforcee repo''s first commit was around 2026-08-07, so the earliest safe submission is roughly 2026-08-21, and only with real commits in between. Also confirm the LICENSE is machine-detectable before submitting. There is no SLA and the maintainer says you may get no response at all; the list is also mid-reorganisation, so Linting may not be the category name by the time you submit. Check the live README section headings on the day.','drafting',null,'CONTRIBUTING.md''s ground rules: one resource per submission, web issue form only (a PR or a gh CLI submission risks an interaction ban), no emojis, no sales pitch, no addressing the reader. The signup/payment blocker is why the Primary Link is the open-source repo and not enforcee.vercel.app, which is a paid hosted service and would be a review blocker. The submission text must be written by hand, the maintainer states verbatim that "resource recommendations must be created by human beings". No compliance/governance/platform/layer wording, and no compaction claim at all, the description says the hook re-injects rules, it does not say anything died.','Raw material from research. Rewrite every sentence in your own words before posting — several of these surfaces ban generated text outright.',1.5,'claude'),
('Reddit (browser, read-only)','other','Open the live sidebars of r/ClaudeAI, r/ClaudeCode, r/cursor and r/SideProject in a normal browser and copy the rule text verbatim into a local file, plus any AutoModerator/karma notice. The recon''s rule text came from the Arctic Shift archive (https://arctic-shift.photon-reddit.com/api/subreddits/r','Week 1 — Close the recon gaps and break your own claims before anyone else does. Nothing public that mentions Enforcee.

Asset needed: rules.md — verbatim sidebar text per sub, dated','scheduled','2026-08-10 09:00+02','Blocked by: Nothing. This is the first gate; every Reddit item downstream is blocked by it.','',0.75,'claude'),
('Hacker News (read-only)','other','Read dang''s explanation of the Show HN flagging wave at https://news.ycombinator.com/item?id=48455315 (returned 429 to the researcher — read it manually), plus https://news.ycombinator.com/item?id=48460938 and https://news.ycombinator.com/item?id=48384741. Also read the comments on https://www.reddi','Week 1 — Close the recon gaps and break your own claims before anyone else does. Nothing public that mentions Enforcee.

Asset needed: launch-risk-checklist.md','scheduled','2026-08-10 09:00+02','Blocked by: Nothing.','',0.5,'claude'),
('Local (claims hardening)','other','Re-run the 10 guard enforcement cases and record the EXACT Claude Code version and the exact tool names they were measured against. https://github.com/anthropics/claude-code/issues/37210 (closed as not planned) reports a well-formed PreToolUse deny with exit code 2 being ignored for the Edit tool, a','Week 1 — Close the recon gaps and break your own claims before anyone else does. Nothing public that mentions Enforcee.

Asset needed: guard-cases.md with version pin + tool list','scheduled','2026-08-10 09:00+02','Blocked by: Nothing. Blocks every item that mentions the guard.','',1.5,'claude'),
('Local (claims hardening)','other','Verify that openai/codex still silently truncates AGENTS.md at 32 KB on a current build (https://github.com/openai/codex/issues/13386, open, filed 2026-03-03). Everything in the week-2 GitHub comment rests on it. If it has been fixed, that is itself a useful contribution to the thread — say so there','Week 1 — Close the recon gaps and break your own claims before anyone else does. Nothing public that mentions Enforcee.

Asset needed: 32kb-check.md with codex version and result','scheduled','2026-08-10 09:00+02','Blocked by: Nothing.','',1.0,'claude'),
('GitHub (own repo)','other','Repo hygiene for the gates ahead: a real MIT LICENSE in the repo root that GitHub''s license detection picks up (awesome-claude-code''s bot reads it), a README that opens with the mechanism and the reproduce command rather than a pitch, and the version pin from Tuesday stated next to the guard claim. ','Week 1 — Close the recon gaps and break your own claims before anyone else does. Nothing public that mentions Enforcee.

Asset needed: LICENSE, README.md, daily commit cadence','scheduled','2026-08-10 09:00+02','Blocked by: Tuesday''s version pin.','',1.0,'claude'),
('Accounts (no posting)','other','Create the Lemmy account on lemmy.world now so the 30-day age gate on /c/selfhosted Rule 7 starts ticking (eligible ~2026-09-11) even though it is not in this six-week plan. Confirm the Hacker News account exists and is older than two weeks by week 6 — a green username plus a product is half the pat','Week 1 — Close the recon gaps and break your own claims before anyone else does. Nothing public that mentions Enforcee.

Asset needed: none','scheduled','2026-08-10 09:00+02','Blocked by: Nothing.','',0.25,'claude'),
('Reddit — r/cursor, comment only','other','Reply to uncivilized_engineer''s thread (https://www.reddit.com/r/cursor/comments/1vigddl/) using the ''my rules are being ignored'' template, rewritten in your own words for that specific question: which rule phrasings are mechanically checkable, which produce no observable trace at all. Cite Ned Cole','Week 1 — Close the recon gaps and break your own claims before anyone else does. Nothing public that mentions Enforcee.

Asset needed: reply template (rewritten, not pasted)','scheduled','2026-08-10 09:00+02','Blocked by: Monday''s sidebar read of r/cursor — its self-promo rule is unverified, so assume the strictest and link nothing.','',0.5,'claude'),
('Reddit — r/ChatGPTCoding, comment only','other','Reply to IcyCaterpillar9096''s ''how do you actually audit what an AI agent changed across a multifile SaaS project?'' (https://www.reddit.com/r/ChatGPTCoding/comments/1visqdg/) with the method only: deterministic checks first, model judge for the residue, evidence quote must literally exist in the out','Week 1 — Close the recon gaps and break your own claims before anyone else does. Nothing public that mentions Enforcee.

Asset needed: reply template (rewritten again, different wording)','scheduled','2026-08-10 09:00+02','Blocked by: Monday''s sidebar read; the Rule 6 sponsorship-via-modmail route makes any promotional post here out of bounds.','',0.5,'claude'),
('Local (experiment)','other','Build and run the paired AGENTS.md repro: the same mechanically-signed rule set duplicated twice in one file, set A well under 32 KB and set B well past it, padded with inert prose so byte offset is the only difference. Run one task that should trigger every rule in both sets; record per rule whethe','Week 2 — Produce the evidence artifacts. Post only where a reproduction earns the right to speak.

Asset needed: public repro directory + raw results table','scheduled','2026-08-17 09:00+02','Blocked by: Week 1''s confirmation that the 32 KB truncation still reproduces.','',2.0,'claude'),
('GitHub — openai/codex issue #25884','other','Post one comment on https://github.com/openai/codex/issues/25884 (open, labels CLI/bug/context/model-behavior) separating ''the rule never reached the model'' from ''the rule reached the model and was not applied'', with the paired repro and YOUR ACTUAL NUMBERS — codex version, model, rule counts per se','Week 2 — Produce the evidence artifacts. Post only where a reproduction earns the right to speak.

Asset needed: GitHub comment draft #2, placeholders filled from Monday''s run','scheduled','2026-08-17 09:00+02','Blocked by: Monday''s repro producing real numbers. If it produced a null result, say that in the comment instead — do not skip the thread.','',0.75,'claude'),
('Local (experiment)','other','Run VERIFY against the most-starred ruleset in the ecosystem — github.com/forrestchang/andrej-karpathy-skills, MIT, ~200.6k stars (recheck the count on the day; unverified programmatically) — over a real session. Export the receipt JSON, the transcript and the exact ruleset to a public artifacts dir','Week 2 — Produce the evidence artifacts. Post only where a reproduction earns the right to speak.

Asset needed: /artifacts/karpathy-skills-audit/ + reproduce command','scheduled','2026-08-17 09:00+02','Blocked by: Nothing, but the attribution must be right: it was written by Forrest Chang, derived from Karpathy''s observations, not by Karpathy (https://blog.alexrusin.com/the-viral-karpathy-claude-md-file-heres-the-honest-truth-about-what-it-actually-is/).','',1.0,'claude'),
('Own blog (drafting, not published)','other','Hand-write blog piece #1: which rules in that ruleset can actually be checked, and which leave nothing behind. Run the file''s own acceptance criteria (''fewer unnecessary changes in diffs... clarifying questions come before implementation''), not your own. State in your own words, before a commenter d','Week 2 — Produce the evidence artifacts. Post only where a reproduction earns the right to speak.

Asset needed: blog piece #1 draft','scheduled','2026-08-17 09:00+02','Blocked by: Wednesday''s artifacts. No draft before the receipts exist.','',1.5,'claude'),
('Hacker News (comments, no self-links)','other','Three substantive comments on threads you would have read anyway. Zero links to Enforcee, zero mentions. This is account aging, not outreach — it is what prevents the auto-flag in week 6.','Week 2 — Produce the evidence artifacts. Post only where a reproduction earns the right to speak.

Asset needed: none','scheduled','2026-08-17 09:00+02','Blocked by: Nothing.','',0.25,'claude'),
('Reddit — r/ClaudeCode, comment only','other','Reply to ximon16182''s ''Anyone else using Claude Code + Codex and getting stuck auditing forever?'' (https://www.reddit.com/r/ClaudeCode/comments/1vissz6/) with the cost argument stated as measurement, not as a pitch. Rewrite the template a third time — identical text across threads is the fastest way','Week 2 — Produce the evidence artifacts. Post only where a reproduction earns the right to speak.

Asset needed: reply template (third rewrite)','scheduled','2026-08-17 09:00+02','Blocked by: Week 1''s sidebar read; the archive records restrict_posting: true for this sub, so confirm what that gate is before commenting.','',0.5,'claude'),
('Own blog (canonical)','other','Finish, self-edit by hand, and publish piece #1 on enforcee.vercel.app with the artifacts directory and the reproduce command inline. It must live here first so any later submission points at the original (HN guideline: ''Please submit the original source''). Crop the star count out of any title; put ','Week 3 — Publish the finding on your own domain. Take the one list slot that is worth taking.

Asset needed: blog piece #1, live, with /artifacts/ linked','scheduled','2026-08-24 09:00+02','Blocked by: Week 2 draft + artifacts + the Forrest Chang attribution check.','',2.0,'claude'),
('Own blog','other','24-48h soak: re-read cold, fix typos, re-verify every external link and the star count as rendered today, confirm the reproduce command works on a clean checkout. Nothing gets submitted anywhere from a page you have not re-read cold.','Week 3 — Publish the finding on your own domain. Take the one list slot that is worth taking.

Asset needed: none','scheduled','2026-08-24 09:00+02','Blocked by: Monday''s publish.','',0.5,'claude'),
('Local (experiment)','other','Measure what actually degrades at compaction. Anthropic documents invoked skill bodies coming back ''capped at 5,000 tokens per skill and 25,000 tokens total; oldest dropped first'' with ''truncation keeps the start of the file'' (https://code.claude.com/docs/en/context-window). Measure the haircut. Sep','Week 3 — Publish the finding on your own domain. Take the one list slot that is worth taking.

Asset needed: compaction measurement + raw logs, CLI version stamped','scheduled','2026-08-24 09:00+02','Blocked by: Nothing, but date-stamp everything: Anthropic now ships an InstructionsLoaded hook and /context, so this surface moves fast.','',2.0,'claude'),
('GitHub — anthropics/claude-code issue #13919','other','Comment on https://github.com/anthropics/claude-code/issues/13919 (''Claude Skills context completely lost after auto-compaction'', OPEN, marked a regression) with the measurement — the reporter''s ''completely lost'' is better explained by a silent size- and order-dependent haircut than by loss. Reprodu','Week 3 — Publish the finding on your own domain. Take the one list slot that is worth taking.

Asset needed: Wednesday''s measurement','scheduled','2026-08-24 09:00+02','Blocked by: Wednesday''s measurement producing a result. No measurement, no comment.','',0.5,'claude'),
('awesome-claude-code (hesreallyhim, 45.2k stars)','other','Submit ONE resource via the web issue form only (https://github.com/hesreallyhim/awesome-claude-code/issues/new?template=recommend-resource.yml). Primary link is the open-source repo, never enforcee.vercel.app — signup or payment is an explicit review blocker. Category Linting (check the live README','Week 3 — Publish the finding on your own domain. Take the one list slot that is worth taking.

Asset needed: submission fields + one-line description (draft #6)','scheduled','2026-08-24 09:00+02','Blocked by: The hard automated gate: repo ≥14 days since first commit on the default branch WITH commits after day one, or 100+ stars. First commit ~2026-08-07 makes 2026-08-21 the earliest safe date. Also blocked by a machine-detectable LICENSE.','',0.5,'claude'),
('Measurement (standing ritual)','other','Record the baseline for every kill gate: GitHub stars, npm weekly downloads, unique referrer hosts and session counts to the blog, any inbound mention of ''Enforcee'' anywhere you did not post, paid conversions. Same file, same time, every Friday. There is no telemetry — these five numbers are the ent','Week 3 — Publish the finding on your own domain. Take the one list slot that is worth taking.

Asset needed: metrics.tsv','scheduled','2026-08-24 09:00+02','Blocked by: Nothing.','',0.25,'claude'),
('Hacker News (comments, no self-links)','other','Three more substantive comments. Still no mentions of Enforcee.','Week 3 — Publish the finding on your own domain. Take the one list slot that is worth taking.

Asset needed: none','scheduled','2026-08-24 09:00+02','Blocked by: Nothing.','',0.25,'claude'),
('dev.to (drafting)','other','Hand-write the dev.to piece as a credited continuation of Mike Dolan''s ''I Wrote 500 Lines of Rules for Claude Code'' (https://dev.to/mikeadolan/...-3c8): hooks fix the rules you can express as a predicate over a tool call, which on a real file is fewer than half of them. New prose, not a re-cut of bl','Week 4 — Syndicate the method to the platform where this genre already lives, and ship the mechanism itself.

Asset needed: dev.to piece draft (opener #4)','scheduled','2026-08-31 09:00+02','Blocked by: Blog #1 live, so the canonical link exists.','',2.5,'claude'),
('dev.to + Hashnode','other','Publish on dev.to with a canonical link back to your own domain; mirror to Hashnode with the canonical tag (Hashnode''s AI policy is the most permissive: permitted with responsibility). Tag claudecode / ai / devtools. Keep the compaction correction to one paragraph in passing — dev.to/rulestack publi','Week 4 — Syndicate the method to the platform where this genre already lives, and ship the mechanism itself.

Asset needed: Monday''s draft','scheduled','2026-08-31 09:00+02','Blocked by: Monday''s draft being hand-typed.','',0.5,'claude'),
('dev.to (thread duty)','other','Answer every comment within 24 hours, with a number or with ''I haven''t measured that.'' Never with an adjective. If someone is right, say so in the thread rather than in an edit.','Week 4 — Syndicate the method to the platform where this genre already lives, and ship the mechanism itself.

Asset needed: none','scheduled','2026-08-31 09:00+02','Blocked by: Publication.','',0.75,'claude'),
('claude-code-templates / aitmpl.com (davila7, 28.2k stars)','other','One PR adding the PreToolUse deny hook and the PostCompact re-injection hook as standalone JSON components under cli-tool/components/hooks/<category>/, following CONTRIBUTING.md''s file structure exactly. Each hook must be genuinely useful with no Enforcee account — a hook behind a signup will not me','Week 4 — Syndicate the method to the platform where this genre already lives, and ship the mechanism itself.

Asset needed: two hook JSON components + PR description','scheduled','2026-08-31 09:00+02','Blocked by: The week-1 version pin — ship the hooks with the Claude Code version and tool types they were verified on written into the component description, not just the README.','',1.25,'claude'),
('Reddit — r/SideProject','other','Smoke-test the headline sentence only. One line of ''I built X because Y'' plus a screenshot of a real per-rule verdict table. This sub''s half-life is minutes and the audience is other founders, not your ICP — the entire point is to find out whether the sentence survives a stranger reading it, cheaply','Week 4 — Syndicate the method to the platform where this genre already lives, and ship the mechanism itself.

Asset needed: one headline sentence + one verdict-table screenshot','scheduled','2026-08-31 09:00+02','Blocked by: Week 1''s sidebar read (this sub returned an empty rules array in the archive — observed behaviour is not a verified rule).','',0.5,'claude'),
('Measurement + Hacker News','other','Friday metrics ritual. Check whether the awesome-claude-code issue has picked up the validation-passed label (the label progression is validation-passed -> approved -> pr-created; no SLA exists and the maintainer says you may get no response). Three more HN comments, no self-links.','Week 4 — Syndicate the method to the platform where this genre already lives, and ship the mechanism itself.

Asset needed: metrics.tsv','scheduled','2026-08-31 09:00+02','Blocked by: Nothing.','',0.5,'claude'),
('Reddit — r/ClaudeAI (drafting)','other','Rewrite the r/ClaudeAI post by hand, folding in whatever the dev.to comments and the r/SideProject smoke test taught you about the headline. Re-read your week-1 copy of Rule 6 and confirm the sidebar still says promotion is allowed with full disclosure of what the user gets, who it helps, and your a','Week 5 — Spend the Reddit post on a headline that has already been tested. Open the one-shot doors that cost one send each.

Asset needed: Reddit post draft #1, rewritten','scheduled','2026-09-07 09:00+02','Blocked by: Week 1 sidebar read; week 3 blog live; week 4 dev.to reception.','',1.25,'claude'),
('Reddit — r/ClaudeAI, flair ''Claude Code Workflow''','other','Post it. Flair is mandatory (Rule 5). Disclosure paragraph near the top, not buried at the bottom. Lead with the measurement — what share of a real ruleset is decided with zero model calls, and what the judge got wrong — not with the product. End with a question. Fallback surface if the sidebar read','Week 5 — Spend the Reddit post on a headline that has already been tested. Open the one-shot doors that cost one send each.

Asset needed: Monday''s draft','scheduled','2026-09-07 09:00+02','Blocked by: Monday''s rewrite; verified Rule 6 text; verified flair list.','',0.5,'claude'),
('Reddit (thread duty)','other','Sit in the thread for the first two hours after posting, then twice a day for 72 hours. Answer every top-level objection once. When someone says the 80% figure comes from your own rulesets, agree — it does, and the post already says so. Never reply twice to the same person in an argument. Never edit','Week 5 — Spend the Reddit post on a headline that has already been tested. Open the one-shot doors that cost one send each.

Asset needed: none','scheduled','2026-09-07 09:00+02','Blocked by: The post.','',1.75,'claude'),
('Console.dev (email)','other','One plain-text email to hello@console.dev. One sentence on what it does, the self-serve no-signup URL, the privacy stance (local ledger, no telemetry), and the four measured numbers with a link to how they were produced. Their published criteria reward exactly this: ''Is it fast?'', ''Does it have any ','Week 5 — Spend the Reddit post on a headline that has already been tested. Open the one-shot doors that cost one send each.

Asset needed: four measured numbers + provenance link + a pre-1.0 label on the site','scheduled','2026-09-07 09:00+02','Blocked by: The site must actually show a self-serve, no-sales-call path, and a beta/pre-1.0 label if you claim the Beta slot.','',0.5,'claude'),
('Changelog News (web form)','other','Submit blog piece #1''s URL at https://changelog.com/news/submit — the ARTICLE, never enforcee.vercel.app. Their exclusions are explicit: ''Products and services require sponsorship instead.'' Fire and forget; they only email you if it runs.','Week 5 — Spend the Reddit post on a headline that has already been tested. Open the one-shot doors that cost one send each.

Asset needed: blog piece #1 URL','scheduled','2026-09-07 09:00+02','Blocked by: Blog piece #1 being live and cold-read (week 3).','',0.25,'claude'),
('awesome-cursorrules (PR) or ClaudeLog (email)','other','Pick one, not both. Either a single PR to PatrickJS/awesome-cursorrules adding one genuinely good rules/<slug>.mdc with the required frontmatter (description, globs, alwaysApply) plus the README category line — a rule contribution, never a tool listing. Or one short email via https://claudelog.com/c','Week 5 — Spend the Reddit post on a headline that has already been tested. Open the one-shot doors that cost one send each.

Asset needed: one .mdc rule file, or one contribution email','scheduled','2026-09-07 09:00+02','Blocked by: Nothing, but skip entirely if the Reddit thread is still live and needs you.','',0.75,'claude'),
('Hacker News (pre-launch readiness) + measurement','other','Friday metrics ritual, then the go/no-go audit for next week: does the HN account have real comment history and non-trivial karma; do you know one person with vouch privileges (>31 karma flags, >501 downvotes — vouching is the documented recovery path from an auto-kill); are the version placeholders','Week 5 — Spend the Reddit post on a headline that has already been tested. Open the one-shot doors that cost one send each.

Asset needed: launch-risk-checklist.md, completed','scheduled','2026-09-07 09:00+02','Blocked by: Weeks 1-4 of comment history. This cannot be manufactured on Friday.','',1.0,'claude'),
('Hacker News (drafting)','other','Final hand-rewrite of the Show HN text and first comment. Every word typed by you — the guidelines say verbatim ''Don''t post generated text or AI-edited text'', which is stricter than a ban on generated text alone; the tables and receipts are data and are fine. Title carries no gratuitous number, no u','Week 6 — Spend the single Show HN. Reddit stands down so HN is the third channel, not the fourth.

Asset needed: Show HN text + founder first comment, hand-typed','scheduled','2026-09-14 09:00+02','Blocked by: Week 1 version pin; week 5 readiness audit; kill gate 5 not having fired.','',1.5,'claude'),
('Own product (dry run)','other','Open enforcee.vercel.app in a clean incognito profile on a machine that has never touched it and complete a full audit with no account and no card. Check rate limits and Vercel plan headroom against front-page traffic — the single most-cited reason Show HNs die is a barrier to trying the thing, and ','Week 6 — Spend the single Show HN. Reddit stands down so HN is the third channel, not the fourth.

Asset needed: none','scheduled','2026-09-14 09:00+02','Blocked by: Monday''s text being final, so the demo matches what the post claims.','',0.75,'claude'),
('Hacker News — Show HN','other','Post it, weekday morning US Eastern. Treat the timing as folklore — no credible current source for HN timing was found, and what actually matters is not launching from a green account. Post the founder paragraph as the first comment immediately. Do not delete and repost under any circumstances. Do n','Week 6 — Spend the single Show HN. Reddit stands down so HN is the third channel, not the fourth.

Asset needed: Monday''s text; a live no-signup demo; the open repo','scheduled','2026-09-14 09:00+02','Blocked by: Tuesday''s dry run; an aged account with real comment history; a known vouch contact.','',0.5,'claude'),
('Hacker News (thread duty)','other','Stay in the thread for the first four hours. Answer every objection once, with a number or with ''I haven''t measured that.'' Concede immediately and publicly when someone is right. The invitation in the post — try to make it accuse you of something you did not do — is real: if a stranger produces a fa','Week 6 — Spend the single Show HN. Reddit stands down so HN is the third channel, not the fourth.

Asset needed: none','scheduled','2026-09-14 09:00+02','Blocked by: The post.','',2.0,'claude'),
('Hacker News + measurement','other','Continue thread duty as it slows. Record referrers, stars, npm downloads and any paid conversions hourly for the first day — this is the only large traffic event in the six weeks and the only chance to see what the funnel actually does under load.','Week 6 — Spend the single Show HN. Reddit stands down so HN is the third channel, not the fourth.

Asset needed: metrics.tsv','scheduled','2026-09-14 09:00+02','Blocked by: The post.','',0.75,'claude'),
('Own blog','other','Publish the first entry in the post-mortem series using the stable URL pattern — one rule violation, the rule text and where it lives, the session, the exact turn, the evidence quote at its character offset, whether the guard would have denied it, and what you changed. If the Show HN produced a genu','Week 6 — Spend the single Show HN. Reddit stands down so HN is the third channel, not the fourth.

Asset needed: post-mortem #1 + metrics.tsv','scheduled','2026-09-14 09:00+02','Blocked by: A real incident. A manufactured one reads as manufactured.','',0.5,'claude'),
('house','other','Standing rules for every post','1. THREE CHANNELS, NAMED. At any moment the active set is exactly: (1) GitHub issue threads — anthropics/claude-code plus openai/codex, counted as one channel, running weeks 1-6; (2) written long-form — own domain canonical, dev.to and its Hashnode mirror, running weeks 2-4; (3) Reddit, weeks 1-5, which stands down after the r/ClaudeAI thread goes quiet so that Hacker News can take the slot in week 6. HN participation before week 6 is comments with zero self-links and zero mentions; that is account aging, not a channel, and if you ever link Enforcee on HN before week 6 you have quietly started a fourth channel.
2. EVERYTHING PUBLISHES ON YOUR OWN DOMAIN FIRST, 24-48 HOURS BEFORE IT IS SUBMITTED ANYWHERE. HN''s guidelines say to submit the original source, and the soak is what catches the typo that makes you look sloppy in front of the exact audience that punishes sloppiness.
3. EVERY WORD OF PROSE IS TYPED BY A HUMAN. HN bans generated AND AI-edited text; dev.to''s AI-assisted-article rules ban promoting your own product in an AI-assisted post and penalise visibility across ALL your posts, not just the offending one; awesome-claude-code requires that recommendations be created by human beings. Your tables, receipts and JSON are data and are fine everywhere. The argument around them is not.
4. CADENCE: at most one item per surface per day, and never the same text twice. Rewrite the reply template in your own words for every thread it is used in — identical comment text across threads is the single fastest way to be read as a bot on Reddit and flagged as spam by GitHub. On GitHub, one comment per thread, never on a closed issue, reproduction first and tool second.
5. BIND EVERY ZERO TO ITS SAMPLE SIZE IN THE SAME SENTENCE. ''Zero fabricated evidence spans across 48 verdicts on three models'', never ''zero fabricated evidence spans'' with the n in a footnote. Say ''48 is a small n'' before someone extracts it from you. The same applies to the 80% figure: it comes from your own rulesets and that is a biased sample, so say so in the post.
6. THE COMPACTION SENTENCE, WORD FOR WORD, EVERY TIME. Project-root CLAUDE.md is re-read from disk and re-injected after /compact. What is documented as lost is paths:-scoped rules until a matching file is read again, nested CLAUDE.md in subdirectories, and invoked skill bodies which return capped at 5,000 tokens per skill and 25,000 total, oldest dropped first, truncation keeping the start of the file (https://code.claude.com/docs/en/context-window). Never say a CLAUDE.md died. This audience has read the docs and will correct you in the first comment.
7. PRE-EMPT THE PRETOOLUSE OBJECTION IN THE POST, NOT IN THE REPLY. State the exact Claude Code version and the exact tool types the 10/10 guard result was measured on, and name https://github.com/anthropics/claude-code/issues/37210 yourself. In this audience, being the person who raised the objection is worth more than the objection never being raised.
8. NEVER LEAD WITH COMPLIANCE, GOVERNANCE, PLATFORM OR LAYER. Use the words the readers actually use: ignored, forgets, drifts, lost after compact, doesn''t follow. Enforcee''s own vocabulary — coverage, verdict, evidence span — belongs in the body, never in a headline.
9. DISCLOSE AT THE TOP, NOT THE BOTTOM. r/ClaudeAI''s Rule 6 asks for exactly three things: what the user gets, who it helps, and your association with the project. Say all three in your own voice before anyone has to find it in your post history.
10. THREAD BEHAVIOUR AFTER POSTING: sit in the thread for the first two hours (four for the Show HN), then twice daily for 72 hours. Answer every top-level objection exactly once. Answer with a number or with ''I haven''t measured that'' — never with an adjective. When someone is right, say so in the thread; do not fix it silently in an edit. Never reply twice to the same person inside an argument. Never ask anyone to upvote anywhere — HN bans soliciting votes and Peerlist bans it outright.
11. LINK THE REPO OR THE WRITEUP, NOT THE HOSTED APP, WHEREVER THE VENUE''S RULES MAKE THE PRODUCT THE PROBLEM: awesome-claude-code treats signup or payment as a review blocker, Changelog News rejects commercial offerings outright, r/LocalLLaMA Rule 4 requires links go directly to the source, r/programming Rule 2 removes direct app-demo links.
12. IF A POST IS REMOVED: do not repost, do not delete and repost, do not argue in modmail. Ask once what to change, and record the answer in rules.md. If a Show HN is flagged, do not resubmit — ask a known established user to vouch, once.
13. FRIDAY MEASUREMENT RITUAL, 15 MINUTES, SAME FILE, SAME TIME. There is no telemetry, so the entire instrument panel is five numbers: npm weekly downloads, GitHub stars, unique referrer hosts and session counts, inbound mentions of ''Enforcee'' anywhere you did not post, and paid conversions. A kill gate you cannot read is not a kill gate.
14. VENUES THAT ARE OFF THE PLAN AND STAY OFF: r/ExperiencedDevs (Rule 8 bans advertisements outright with only a modmail exemption), r/programming (Rule 5 bans without warning; earn it later with a post-mortem and a real comment history), r/webdev (Showoff Saturday only, and its commercial-promotion rule carries a ban), Lobsters (invite-only, you cannot join on demand), Cursor forum Showcase (verified 7-50 views per topic), TLDR / The Neuron / Bytes / Pointer / Cooper Press (no free intake or wrong audience), tairov/awesome-agents.md (archived 2026-01-26).
15. HELD IN RESERVE, DELIBERATELY UNSPENT IN THESE SIX WEEKS: the r/indiehackers SHOW IH post is a one-time-per-product allowance and must not be spent until the headline sentence has survived Reddit and HN; the r/programming post-mortem waits for a real comment history; Lemmy /c/selfhosted waits out its 30-day account clock (create the account in week 1 regardless).','idea',null,'Read before posting anywhere.','',0,'claude'),
('house','other','Kill gates — pre-committed','1. BASELINE FIRST: Friday of week 3 is the zero point for every number below — stars, npm weekly downloads, referrer sessions, mentions, paid conversions. A gate compared against a number you never wrote down is a rationalisation.
2. WEEK 3 GATE — THE ARTIFACT. If blog piece #1 plus the two GitHub comments produce fewer than 25 unique referred sessions from github.com and reddit.com combined in their first seven days, the problem is the writing, not the channel. ACTION: cancel the week-4 dev.to draft and spend those 2.5 hours rewriting the headline sentence and the opening 200 words. Do not publish a second piece off the back of a first one nobody read.
3. WEEK 4 GATE — DEV.TO. If the dev.to piece has fewer than 5 comments and sends fewer than 50 sessions to your domain within seven days of publishing, ACTION: do not cross-post there again, drop dev.to from the three-channel set for the rest of the plan, and give the slot back to GitHub issue threads (5-8 threads over the remaining weeks, one comment each).
4. WEEK 4 GATE — CURATED LISTS. If the awesome-claude-code issue is closed by the bot, or is still unlabelled 10 days after submission, ACTION: stop submitting to curated lists entirely for the rest of the six weeks (no OpenAlternative, no DevHunt, no Uneed). Lists are not the bottleneck; the hours go to GitHub issue threads instead.
5. WEEK 5 GATE — REDDIT. Under 30 upvotes and under 10 comments within 48 hours of the r/ClaudeAI post: ACTION: Reddit is not your channel. Do not post to r/ClaudeCode, do not spend the r/indiehackers SHOW IH one-shot, drop to comments-only for the rest of the plan. If the post is removed by a mod: ACTION: stop posting to Reddit entirely for the remaining weeks, ask the mods once what to change, and record it.
6. WEEK 5 GATE — SHOW HN GO/NO-GO (the hard one). Fire if ANY of these is true on Friday 2026-09-11: the repo has gained fewer than 25 stars since the week-3 baseline; the HN account has thin comment history or is under two weeks old; you cannot name one person with vouch privileges; the free no-signup audit does not complete for a stranger in incognito with no card; the Claude Code version and tool types behind the 10/10 guard result are not written into the post. ACTION: do not run the Show HN in week 6. Postpone it to a later month and spend week 6 on GitHub issue threads. A new-ish account plus a product plus a starless repo is the exact pattern currently being flagged, and you only get one Show HN.
7. WEEK 6 GATE — SHOW HN OUTCOME. Flagged or killed within two hours: ACTION: do not repost, do not delete, ask once for a vouch, and treat HN as closed for three months. Under 15 points after four hours: ACTION: stop working the thread after hour four rather than bumping it, and do not submit the benchmark piece to HN in the following quarter.
8. INSTALL-PATH GATE — NPM. If the guard package is under 30 weekly downloads by the end of week 6 while GitHub stars are rising, the install experience is broken, not the pitch. ACTION: stop all outreach for two weeks and fix the install path. Rising stars with flat downloads means people liked the idea and could not run it.
9. PRICING GATE — PAID CONVERSIONS. Zero paid conversions by the end of week 6 against more than 200 unique referred sessions: ACTION: do not add a channel and do not post more. The paywall is in the wrong place. Re-price or move the line between the free audit and the paid product before spending another marketing hour.
10. WORD-OF-MOUTH GATE — INBOUND MENTIONS. If by the end of week 6 nobody has mentioned Enforcee anywhere you did not personally post (search GitHub, dev.to, X and the open web for the name weekly), you have distribution without recommendation. ACTION: stop all outreach for four weeks and build. More posting cannot fix a product nobody repeats.
11. CREDIBILITY GATE — ABSOLUTE, FIRES AT n=1. One credible report from a stranger of a false accusation, a fabricated evidence span, or a PreToolUse deny that did not hold: ACTION: stop every posting activity that same day, reproduce it, and publish the failure on your own blog before posting anything else anywhere. This audience forgives a bug and does not forgive a quiet fix. It is also the only gate where a single observation is enough.','idea',null,'No telemetry exists, so these are observable numbers only.','',0,'claude');
